### ISSUE TITLE
find a bug about dialog.php for subfolder

### ISSUE THREAD

**Issue by mbdmt** [Kwaadpepper/laravel-responsivefilemanager#10]
3 questions
1 )
a bug in line 106
if (!session()->has('RF.subfolder')....
this is not working for subfolder
have to remove "!"

2 )
In addition, there are bugs that have been reacted
If you select the type in the list, all thumbnails will become the same

3 )
I want to modify the file name (for example: 20200816122300.jpg), when the file name is a special symbol or Chinese text
are there any good suggestions.

thanks

**Comment by Kwaadpepper** [comment]
Thank you for reporting this I will take a look at it asap.
Could you explain a bit more 3) I am not sure to understand it.

**Comment by Kwaadpepper** [comment]
Please update to 0.0.10 I believe I have fixed your issues.
