### ISSUE TITLE
When uploading files, the process did not stop, files were not uploaded.

### ISSUE THREAD

**Issue by YaroslavFedan** [Kwaadpepper/laravel-responsivefilemanager#11]
The solution that helped was to replace in dialog.php
//blueimp.github.io/JavaScript-Load-Image/js/load-image.all.min.js
at
//cdnjs.cloudflare.com/ajax/libs/blueimp-load-image/2.18.0/load-image.all.min.js

**Comment by Kwaadpepper** [comment]
Could you provide error from console please so I could study your case ?

**Comment by YaroslavFedan** [comment]
![process-all-times](https://user-images.githubusercontent.com/8318982/91288363-955af480-e799-11ea-9443-232daa70f2bf.png)

**Comment by Kwaadpepper** [comment]
I changed lib with cloudflare ones, it seems better, I will bump version in few hours. Let me know how it goes, sorry for the delay.

**Comment by Kwaadpepper** [comment]
Hey I was merging from the original lib and I noticed that Blueimp image-load was causng this.
I made a fix it will be released soon.
Thank you for reporting this.
