### ISSUE TITLE
Unexpectedly change timezone of whole project 

### ISSUE THREAD

**Issue by babak271** [Kwaadpepper/laravel-responsivefilemanager#14]
This package has changed the timezone of my project to `Europe/Rome` and it was due to this line `date_default_timezone_set('Europe/Rome');` where is in `src/http/boot'.

It took me a huge effort to find the real problem.
Please obey laravel structure and get timezone from `config('app.timezone');`

**Comment by Kwaadpepper** [comment]
Thank you for reporting this, there are many changes that still should be done in this adaptation project. I will make the corrections. But I don't have much time to continue this project. Please don't hesitate to report any other issue.

Thanks I will push the correction in minutes.
