### ISSUE TITLE
error 500 trying to upload - 

### ISSUE THREAD

**Issue by marcosdipaolo** [Kwaadpepper/laravel-responsivefilemanager#3]
Hi there, thanks for putting this package together.

trying to upload an image i get:
`Internal Server Error 500` and in the console:  
`GET http://localhost:9090/filemanager/upload.php 500 (Internal Server Error)`  
`POST http://localhost:9090/filemanager/upload.php 500 (Internal Server Error)`  

should I configure something else? 
If i see the error it's complaining about upload.php, line 17, `The use statement with non-compound name 'Exception' has no effect`:
```php
use \Exception;
use \stdClass;
```
If I remove them entirely the error changes, it goes: ` SyntaxError: Unexpected token < in JSON at position 0`

Thanks a lot in advance!

**Comment by Kwaadpepper** [comment]
I think you may use a to old version of php maybe. Which version are you using ?

**Comment by marcosdipaolo** [comment]
php 7.2.18

**Comment by wikirex** [comment]
I got the same problem with PHP 7.2.12 on windows 10.
Here is the complete trace:
[https://www.dropbox.com/s/3fpbmxxw452dh2b/rfm_upload_error.txt?dl=0](url)

**Comment by NeuroPastor** [comment]
same error php 7.4.
How fix it?

**Comment by Kwaadpepper** [comment]
just published a fix let me know if this solves the issue. Thanks

**Comment by Kwaadpepper** [comment]
I will let it open till i have more returns on this.

**Comment by NeuroPastor** [comment]
Now other error on upload file
`ErrorException {#539
  #message: "Trying to access array offset on value of type null"
  #code: 0
  #file: "/home/uuu/web/devdo/public_html/vendor/kwaadpepper/laravel-responsivefilemanager/src/ResponsiveFileManager/UploadHandler.php"
  #line: 553
  #severity: E_NOTICE
  trace: {
    /home/uuu/web/devdo/public_html/vendor/kwaadpepper/laravel-responsivefilemanager/src/ResponsiveFileManager/UploadHandler.php:553 {}
    /home/uuu/web/devdo/public_html/vendor/kwaadpepper/laravel-responsivefilemanager/src/ResponsiveFileManager/UploadHandler.php:655 {}
    /home/uuu/web/devdo/public_html/vendor/kwaadpepper/laravel-responsivefilemanager/src/ResponsiveFileManager/UploadHandler.php:1252 {}
    /home/uuu/web/devdo/public_html/vendor/kwaadpepper/laravel-responsivefilemanager/src/ResponsiveFileManager/UploadHandler.php:1553 {}
    /home/uuu/web/devdo/public_html/vendor/kwaadpepper/laravel-responsivefilemanager/src/ResponsiveFileManager/UploadHandler.php:238 {}
    /home/uuu/web/devdo/public_html/vendor/kwaadpepper/laravel-responsivefilemanager/src/ResponsiveFileManager/UploadHandler.php:221 {}
    /home/uuu/web/devdo/public_html/vendor/kwaadpepper/laravel-responsivefilemanager/src/Http/upload.php:196 {}
    /home/uuu/web/devdo/public_html/vendor/kwaadpepper/laravel-responsivefilemanager/src/Http/routes.php:28 {}
    /home/uuu/web/devdo/public_html/vendor/laravel/framework/src/Illuminate/Routing/Route.php:205 {}
    /home/uuu/web/devdo/public_html/vendor/laravel/framework/src/Illuminate/Routing/Route.php:179 {}
    /home/uuu/web/devdo/public_html/vendor/laravel/framework/src/Illuminate/Routing/Router.php:681 {}
    /home/uuu/web/devdo/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:130 {}
    /home/uuu/web/devdo/public_html/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php:41 {}
    /home/uuu/web/devdo/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:171 {}
    /home/uuu/web/devdo/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php:76 {}
    /home/uuu/web/devdo/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:171 {}
    /home/uuu/web/devdo/public_html/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php:49 {}
    /home/uuu/web/devdo/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:171 {}
    /home/uuu/web/devdo/public_html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php:56 {}
    /home/uuu/web/devdo/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:171 {}
    /home/uuu/web/devdo/public_html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php:37 {}
    /home/uuu/web/devdo/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:171 {}
    /home/uuu/web/devdo/public_html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php:66 {}
    /home/uuu/web/devdo/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:171 {}
    /home/uuu/web/devdo/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:105 {}
    /home/uuu/web/devdo/public_html/vendor/laravel/framework/src/Illuminate/Routing/Router.php:683 {}
    /home/uuu/web/devdo/public_html/vendor/laravel/framework/src/Illuminate/Routing/Router.php:658 {}
    /home/uuu/web/devdo/public_html/vendor/laravel/framework/src/Illuminate/Routing/Router.php:624 {}
    /home/uuu/web/devdo/public_html/vendor/laravel/framework/src/Illuminate/Routing/Router.php:613 {}
    /home/uuu/web/devdo/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:170 {}
    /home/uuu/web/devdo/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:130 {}
    /home/uuu/web/devdo/public_html/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php:65 {}
    /home/uuu/web/devdo/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:171 {}
    /home/uuu/web/devdo/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php:76 {}
    /home/uuu/web/devdo/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:171 {}
    /home/uuu/web/devdo/public_html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php:56 {}
    /home/uuu/web/devdo/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:171 {}
    /home/uuu/web/devdo/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php:21 {}
    /home/uuu/web/devdo/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:171 {}
    /home/uuu/web/devdo/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php:21 {}
    /home/uuu/web/devdo/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:171 {}
    /home/uuu/web/devdo/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php:27 {}
    /home/uuu/web/devdo/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:171 {}
    /home/uuu/web/devdo/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php:63 {}
    /home/uuu/web/devdo/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:171 {}
    /home/uuu/web/devdo/public_html/vendor/fideloper/proxy/src/TrustProxies.php:57 {}
    /home/uuu/web/devdo/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:171 {}
    /home/uuu/web/devdo/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:105 {}
    /home/uuu/web/devdo/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:145 {}
    /home/uuu/web/devdo/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:110 {}
    /home/uuu/web/devdo/public_html/public/index.php:55 {
      › $response = $kernel->handle(
      ›     $request = Illuminate\Http\Request::capture()
      › );
    }
  }
}

array:1 [
  "files" => array:1 [
    0 => array:4 [
      "name" => "757677.jpeg"
      "error" => "Trying to access array offset on value of type null"
      "size" => 752220
      "type" => "image/jpeg"
    ]
  ]
]
`

**Comment by Kwaadpepper** [comment]
I have to say that the lib used by Responsive File Manager is way too old.
It misses many fixes and is modified to include FTP.
I shall rewrite this plugin to use internal Laravel functions.
See https://github.com/blueimp/jQuery-File-Upload/blob/master/server/php/UploadHandler.php

I included small fixes to by pass this error i will update the package soon.
