### ISSUE TITLE
call to undefined function session() in dialog.php

### ISSUE THREAD

**Issue by rfrkk** [Kwaadpepper/laravel-responsivefilemanager#5]
1. Laravel Framework 6.11.0
2. tinymce 5 lastest

step1.
composer require kwaadpepper/laravel-responsivefilemanager
then i could see vendor folder be added kwaadpepper folder

step2.
add Kwaadpepper\ResponsiveFileManager\FileManagerServiceProvider::class to config/app.php

step3.
php artisan vendor:publish --provider="Kwaadpepper\ResponsiveFileManager
\FileManagerServiceProvider"
Unable to locate publishable resources.
Publishing complete.

but it has showing "Unable to locate publishable resources." in line 1

step4.
In tinymce 5, i startup ResponsiveFileManager always showing "call to undefined function session() in dialog.php"

**Comment by Kwaadpepper** [comment]
I test with laravel6, there was maybe a psr-4 issues.vendor publish is working here.
you can try composer update if you still have your project

**Comment by Kwaadpepper** [comment]
Please let me know if this is solved by now.
