### ISSUE TITLE
Found a few problems for Laravel 5.5 + L-RF0.7

### ISSUE THREAD

**Issue by mbdmt** [Kwaadpepper/laravel-responsivefilemanager#9]
1. If select to "List View" then thumbs image path error
"/" Is missing in front of the thumbs image path

2. An error will occur if you change the sorting to "Type"
errorinfo:
[DOM] Found 2 elements with non-unique id #form3: (More info: https://goo.gl/9p2vKq) 

3.The first time the sub-directory enters, the picture is not displayed,
Return to the upper directory and re-enter the picture to display
But i set filemanager_subfolder: './',  in tinymce.init
Can solve this problem.

**Comment by Kwaadpepper** [comment]
Thanks for reporting this.
I don't really understand the relation between your Google link  and this issue.

I fixed your first point. Could you provide a capture or tell me the browser you are using  ? It would be easier to track the issue.

As for your third point : 

```The first time the sub-directory enters``` What steps have you done before that, so I could reproduce the error ?

**Comment by Kwaadpepper** [comment]
Ok i just found out your second point, there is an issue with the sort function I can reproduce this.

I still don't know how to reproduce your third point.

> 3.The first time the sub-directory enters, the picture is not displayed,
Return to the upper directory and re-enter the picture to display
But i set filemanager_subfolder: './', in tinymce.init
Can solve this problem.

**Comment by mbdmt** [comment]
about  third point
I said earlier that you can set filemanager_subfolder:'./' to make corrections
But later I found out that I could not upload files.
I do not know why either @@
